<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>optimizing_gratuitiy</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4d96db332f33ef296d8e0919d4f30bf1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.pdf"> <i class="bi bi-file-pdf" role="img">
</i> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/saumi-rahnamay/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
  <div class="quarto-categories">
    <div class="quarto-category">R</div>
    <div class="quarto-category">Visualization</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="optimizing-gratuity" class="level1">
<h1>Optimizing Gratuity</h1>
</section>
<section id="preface" class="level1">
<h1>Preface</h1>
<p>This is the first part of an ongoing project analyzing the data surrounding my part time job as a pizza delivery driver. This project originally started as an assignment for POL 315 at SFU. I returned to it later in 2022 to fully flesh it out.</p>
</section>
<section id="section-i.-research-question-theory-and-hypotheses" class="level1">
<h1>Section I. Research Question, Theory, and Hypotheses</h1>
<p>I work a part-time job as a delivery driver at a pizza restaurant called “Me-n-Ed’s”, located in Port Coquitlam, BC, and it’s a great job! Management is very flexible with scheduling, and the restaurant uses company cars to make deliveries which are fueled and serviced by company dollars. While wage comprises the majority of a driver’s dollars per hour, tips also greatly influence our bottom line. Say I work 5 hours at $15.20/h, making 40 dollars in tips will increase my dollars per hour to 23.20! For comparison, according to indeed.com, the average salary for a lifeguard in BC is 22.65 dollars per hours, which is less than what I make delivering pizzas. Nevertheless, 40 isn’t always what we make. Sometimes, we make as little as 15 dollars in tips, which only increases one’s dollars per hour to 18.20. My goal is to maximize my tips by any means available to me.</p>
<p>What could account for this variance in tips? Some obvious factors are the amount of deliveries a driver takes during their shift and how much pizza they sell over all; more frequent and bigger sales are intuitively correlated with more tip money. How could I maximize these factors then? As is always the case with restaurants some days of the week are busier than others, and on busier days drivers take more deliveries (and therefore make more money). This means I have some means of controlling my tips by scheduling myself to work on the busiest days. I asked some co-workers what they though the busiest day of the week was, and there was a general consensus among drivers that either Fridays or Saturdays are the busiest. Since I typically work three days per week, I want to know on which three days I would end my shift with the highest tip-outs. (A note on vocabulary: I use the terms “Tip-out” and “Cash-out” interchangeably to refer to the amount of dollars in tips I make on a given day).</p>
<p>My main hypothesis is that on average, the highest total tip-outs are on Saturdays, followed by Fridays, followed by Sundays, i.e.&nbsp;weekends. To confidently demonstrate this ranking, I essentially have to make a complete ranking of each day of the week from best to worst in terms of average tips. In the case that I cannot confidently demonstrate this, I also make the logically weaker (but easier to prove) hypothesis that on average, my tips are better on weekends. Instead of ranking 7 categories representing each day of the week, we are simply comparing two categories: Fridays, Saturdays and Sundays (Weekends), compared to Mondays, Tuesdays, Wednesdays, and Thursdays (Weekdays).<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>I was also curious about the roll the weather plays in the customers decision to tip. I’m not primarily interested in the correlation between rain and tips because it’s not something I can control to maximize my tips, but I figured it might be a significant variable to control for.</p>
</section>
<section id="section-ii.-preliminary-work" class="level1">
<h1>Section II. Preliminary Work</h1>
<p>In Section II, I explain what data I’m using to conduct my research as well as an explanation of each variable. Furthermore, I demonstrate how I loaded, categorized and checked for data sanity in my data. I give more details on this process in the R-code blocks below in the form of notes.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#loading data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:</span><span class="sc">\\</span><span class="st">Everything</span><span class="sc">\\</span><span class="st">School</span><span class="sc">\\</span><span class="st">Me n Eds Sales Slips Data"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"Slips.xlsx"</span>) <span class="co">#Sales receipts</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Sales Receipts</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating a column to represent tips as a ratio of the sale amount.</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>TipPercent <span class="ot">&lt;-</span> <span class="fu">round</span>(s<span class="sc">$</span>Tip<span class="sc">/</span>s<span class="sc">$</span>Amount <span class="sc">*</span> <span class="dv">100</span>) </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Weekend <span class="ot">&lt;-</span> s<span class="sc">$</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="co"># Adding a Weekend dummy variable </span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Weekend[s<span class="sc">$</span>Weekend <span class="sc">==</span> <span class="st">"Mon"</span><span class="sc">|</span>s<span class="sc">$</span>Weekend <span class="sc">==</span><span class="st">"Tue"</span><span class="sc">|</span>s<span class="sc">$</span>Weekend <span class="sc">==</span><span class="st">"Wed"</span><span class="sc">|</span>s<span class="sc">$</span>Weekend <span class="sc">==</span><span class="st">"Thu"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Weekend[s<span class="sc">$</span>Weekend <span class="sc">==</span> <span class="st">"Fri"</span><span class="sc">|</span>s<span class="sc">$</span>Weekend <span class="sc">==</span><span class="st">"Sat"</span><span class="sc">|</span>s<span class="sc">$</span>Weekend <span class="sc">==</span><span class="st">"Sun"</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Weekend <span class="ot">&lt;-</span> <span class="fu">factor</span>(s<span class="sc">$</span>Weekend, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>), </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Weekday"</span>, <span class="st">"Weekend"</span>)) </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Precipitation[s<span class="sc">$</span>Precipitation <span class="sc">==</span> <span class="fl">0.0</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Precipitation[s<span class="sc">$</span>Precipitation <span class="sc">&gt;</span><span class="fl">0.0</span> <span class="sc">&amp;</span> s<span class="sc">$</span>Precipitation<span class="sc">&lt;=</span><span class="fl">2.5</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Precipitation[s<span class="sc">$</span>Precipitation <span class="sc">&gt;</span><span class="fl">2.5</span> <span class="sc">&amp;</span> s<span class="sc">$</span>Precipitation<span class="sc">&lt;=</span><span class="fl">10.0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Precipitation[s<span class="sc">$</span>Precipitation <span class="sc">&gt;</span> <span class="fl">10.0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">#Classifying rain levels</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span>Precipitation <span class="ot">&lt;-</span> <span class="fu">factor</span>(s<span class="sc">$</span>Precipitation, <span class="at">levels=</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">3</span>),</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Moderate Rain"</span>, <span class="st">"Light Rain"</span>, <span class="st">"No Rain"</span>, <span class="st">"Heavy Rain"</span>)) </span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-ordering day of the week variable so Friday (day with most observations) is reference category</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(s<span class="sc">$</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>))</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>s<span class="sc">$</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">relevel</span>(s<span class="sc">$</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span>, <span class="at">ref=</span><span class="st">"Fri"</span>) </span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>tpp <span class="ot">&lt;-</span> <span class="fu">ddply</span>(s, <span class="fu">c</span>(<span class="st">"Date"</span>, <span class="st">"`Day of Week`"</span>, <span class="st">"Weekend"</span>, <span class="st">"Precipitation"</span>), summarize, <span class="co">#Compiling by Date</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">TipSum =</span> <span class="fu">sum</span>(Tip), <span class="co">#Cash-out</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>             <span class="at">AmountSum =</span> <span class="fu">sum</span>(Amount), <span class="co">#Total sales amount on a given day (this includes tips)</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>             <span class="at">TipSumLog =</span> <span class="fu">log</span>(TipSum), <span class="co">#Log transformation in anticipation of non-normality</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>             <span class="at">TipPercent =</span> TipSum<span class="sc">/</span>AmountSum<span class="sc">*</span><span class="dv">100</span>) <span class="co">#Tip Percent Frequencies </span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>tpp <span class="ot">&lt;-</span> tpp[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">37</span>), ]</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tpp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##         Date Day of Week Weekend Precipitation TipSum AmountSum TipSumLog
## 1 2022-01-07         Fri Weekend    Heavy Rain  10.31     68.84  2.333114
## 2 2022-01-08         Sat Weekend Moderate Rain   8.83     49.04  2.178155
## 3 2022-01-09         Sun Weekend    Light Rain  13.33     92.87  2.590017
## 4 2022-01-10         Mon Weekday Moderate Rain   7.36     40.90  1.996060
## 5 2022-01-11         Tue Weekday    Heavy Rain   8.20     54.60  2.104134
## 6 2022-01-12         Wed Weekday    Heavy Rain   7.44     37.22  2.006871
##   TipPercent
## 1   14.97676
## 2   18.00571
## 3   14.35340
## 4   17.99511
## 5   15.01832
## 6   19.98925</code></pre>
<p>This data set, labeled “Slips”, is data I manually collected and compiled starting in January of this year (2022) until late March. My data source was sales receipts. Sales receipts are receipts printed from a credit machine when a customer pays for their order at the door as proof of purchase. The credit machine prints two receipts, one for the customer and one for the driver. If the customer does not want their receipt - which is often the case - the driver will discard their extra receipt in a paper bag in the company car they’re driving that day. Once a week, I would collect each paper bag at the end of my shift and compile them into an excel spreadsheet.</p>
<p>Each receipt only had three relevant pieces of information printed on it: The price of the customers order in dollars, The amount the customer tipped in dollars, and the <em>date</em> of the transaction. After compiling around 350 receipts, I used an excel formula to determine the day of the week of the listed dates, and then reduced that to either Weekend or Weekday in R labelled <em>Day of Week`</em> and <em>Weekend</em> respectively. Furthermore, I found the percent the customer tipped on their order by dividing the tip amount by the order amount and multiplying by 100. Next, I made Friday the reference category of my Day of the Week variable because it had the highest <img src="https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&amp;space;%5Cbg_white&amp;space;n" title="n" class="img-fluid" alt="n"> value.</p>
<p>Next, I compiled all this data into another data frame sorted by Date. For instance, I took two deliveries on January 7th, and made 5.31 on the first one, and then 5.00 on the second one in tips. I simply took the sum of all these values for a given date (10.31) and listed them in one row, under the <em>TipSum</em> variable. In other words; <em>TipSum</em> represents my cash-out on any given date. I did the same for the order amount, labelled <em>AmountSum</em>. In precautionary anticipation of any skewedness in my data, I’m including a log-transformation of my cash-out variable, labelled <em>TipSumLog</em>, where TipSumLog = log(TipSum).<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Finally, I gathered some historical precipitation data from an online resource (<a href="https://pittmeadows.weatherstats.ca/charts/precipitation-daily.html" class="uri">https://pittmeadows.weatherstats.ca/charts/precipitation-daily.html</a>), and added <em>precipitation</em> values in millimeters for each date in my data set. I decided to categorize the numeric precipitation values into 4 different categories: No Rain, Light Rain, Moderate Rain and Heavy Rain.</p>
<p>To summarize, my main outcome variable is cash-out amount (Numeric, dollars), my independent variables include Day of the Week (Categorical), Weekend/Weekday Status (Dummy variable), Order amount delivered (Numeric, dollars) and Rain levels (Categorical), all sorted by the Date (Timeseries). Due to the nature of the data collection process, there were one or two missing values caused by typos, which were corrected in the data processing stage.</p>
</section>
<section id="section-iii.-estimate-your-ols-models" class="level1">
<h1>Section III. Estimate Your OLS Models</h1>
<p>Section III involves looking at the relationship between my main independent variable and the outcome I am interested in. First, I will look at the bivariate relationship. Then I will look at a more extensive multivariate analysis and interpret the results for both hypotheses.</p>
<section id="section-iii-part-1.-bivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="section-iii-part-1.-bivariate-analysis">Section III, Part 1. Bivariate analysis</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tpdlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSum <span class="sc">~</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span>, <span class="at">data =</span> tpp)  <span class="co"># Defining the linear model representing the bivariate relationship between TipSum and the Day of the Week for hypothesis 1</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tpdlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSum ~ `Day of Week`, data = tpp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -41.32 -17.59  -6.99   9.82  94.71 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       40.2808     8.0140   5.026  4.4e-06 ***
## `Day of Week`Mon -14.2190    11.5882  -1.227    0.224    
## `Day of Week`Tue -15.8708    11.8867  -1.335    0.187    
## `Day of Week`Wed  -0.3965    13.2031  -0.030    0.976    
## `Day of Week`Thu -17.8696    12.6713  -1.410    0.163    
## `Day of Week`Sat   9.8692    11.5882   0.852    0.398    
## `Day of Week`Sun  -5.3836    11.5882  -0.465    0.644    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 27.76 on 63 degrees of freedom
## Multiple R-squared:  0.1144, Adjusted R-squared:  0.03001 
## F-statistic: 1.356 on 6 and 63 DF,  p-value: 0.2464</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tpwlm <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSum <span class="sc">~</span> Weekend, <span class="at">data =</span> tpp)  <span class="co"># Defining the linear model representing the bivariate relationship between TipSum and the Weekend dummy variable for hypothesis 2</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tpwlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSum ~ Weekend, data = tpp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.882 -18.343  -6.676   7.905 103.128 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      27.479      4.576   6.005 8.35e-08 ***
## WeekendWeekend   14.253      6.567   2.170   0.0335 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 27.46 on 68 degrees of freedom
## Multiple R-squared:  0.06479,    Adjusted R-squared:  0.05104 
## F-statistic: 4.711 on 1 and 68 DF,  p-value: 0.03347</code></pre>
<p>Regarding my first hypothesis, the bivariate regression between the calendar day and cash-outs of all given dates does not produce any significant results; we cannot say with certainty that any particular day of the week is correlated with higher tip-outs. I could not even begin to reject the main null hypothesis based on these results.</p>
<p>Turning to my second hypothesis, the bivariate regression between weekday/weekend status and cash-outs does produce significant results. We see that on average, weekends are correlated with a $14.25 increase in tips compared to weekdays: on average I make around $27.48 in tips on weekdays and $41.73 on weekends.</p>
<p>Though accounting for our control variables for our first hypothesis would theoretically produce a more accurate model, given the sheer insignificance of these results a more precise model in the form of a multiple regression analysis isn’t likely to produce results sufficient to reject the null. Unlike the bivariate regression of our first model, the model for our second hypothesis could very well benefit from the addition of precipitation and order amount as control variables. It’s completely possible that accounting for these two un-modeled variables could rob significance from our results above.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># visual representation of average tips for each research category and their respective hypotheses</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>tpp, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span>, <span class="at">y=</span>TipSum)) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"summary"</span>, <span class="fu">aes</span>(<span class="at">fill=</span><span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span>), <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">""</span>, <span class="at">y=</span><span class="st">"Tips ($)"</span>)<span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>()<span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)<span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Average Tips by Day of Week"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec3-biv-graphic-1.png" class="img-fluid"><!-- --></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>tpp, <span class="fu">aes</span>(<span class="at">x=</span>Weekend, <span class="at">y=</span>TipSum)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">"summary"</span>, <span class="fu">aes</span>(<span class="at">fill=</span>Weekend), <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">""</span>, <span class="at">y=</span><span class="st">"Tips ($)"</span>)<span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_economist</span>()<span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm)<span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>))<span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Average Tips by Weekday/Weekend"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec3-biv-graphic-2.png" class="img-fluid"><!-- --></p>
</section>
<section id="section-iii-part-2.-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="section-iii-part-2.-multiple-regression">Section III, Part 2. Multiple Regression</h2>
<div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tpdlmm <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSum <span class="sc">~</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation, <span class="at">data=</span> tpp) <span class="co"># Defining the multivariate model representing multiple regressions analysis</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tpdlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSum ~ `Day of Week` + AmountSum + Precipitation, 
##     data = tpp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.6835  -2.8527   0.8836   3.6846  11.7521 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             -1.70692    2.14829  -0.795   0.4301    
## `Day of Week`Mon         2.69317    2.41052   1.117   0.2684    
## `Day of Week`Tue         1.82903    2.49356   0.734   0.4662    
## `Day of Week`Wed         4.42647    2.70523   1.636   0.1071    
## `Day of Week`Thu        -0.16291    2.66630  -0.061   0.9515    
## `Day of Week`Sat         3.76959    2.39709   1.573   0.1212    
## `Day of Week`Sun         5.83434    2.44290   2.388   0.0201 *  
## AmountSum                0.13590    0.00364  37.340   &lt;2e-16 ***
## PrecipitationLight Rain -0.34361    2.01601  -0.170   0.8652    
## PrecipitationNo Rain     0.47589    1.91859   0.248   0.8050    
## PrecipitationHeavy Rain -1.41900    1.86852  -0.759   0.4506    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.663 on 59 degrees of freedom
## Multiple R-squared:  0.9655, Adjusted R-squared:  0.9596 
## F-statistic: 165.1 on 10 and 59 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>tpwlmm <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSum <span class="sc">~</span> Weekend <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation, <span class="at">data=</span>tpp) <span class="co"># Doing the same for the second hypothesis</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tpwlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSum ~ Weekend + AmountSum + Precipitation, data = tpp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.7999  -2.3041   0.7308   2.9308  14.1873 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              0.160096   1.480976   0.108    0.914    
## WeekendWeekend           0.890127   1.457937   0.611    0.544    
## AmountSum                0.135727   0.003616  37.539   &lt;2e-16 ***
## PrecipitationLight Rain  0.101026   2.037916   0.050    0.961    
## PrecipitationNo Rain     0.954759   1.894097   0.504    0.616    
## PrecipitationHeavy Rain -0.718763   1.863535  -0.386    0.701    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.826 on 64 degrees of freedom
## Multiple R-squared:  0.9604, Adjusted R-squared:  0.9573 
## F-statistic: 310.2 on 5 and 64 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>When controlling for the order amount and the rain level we can see that the order amount is significantly correlated with higher tips for both hypotheses. In both cases, we see that a one dollar increase in the order amount is correlated with a roughly $0.14 increase in tips. This makes a lot of sense, because tipping 15% of the order amount is considered the norm, and a $0.14 increase in tips for every dollar increase in amount is roughly a 15% increase. Furthermore, we saw that precipitation was not significantly correlated with cash-outs.</p>
<p>Regarding our first hypothesis, we now see that Sundays are significantly correlated with a $5.83 increase in tips compared to Friday. Though this result is significant, it is not enough information to confirm our hypothesis, because we don’t have significant values for Saturday or Friday to compare Sunday to. This confirms my suspicion that multiple regression does not make any progress in confirming my main hypothesis.</p>
<p>Regarding our second hypothesis, weekends are no longer significantly correlated with tips. This undermines our capacity to confirm our second hypothesis, and reject our second null.</p>
</section>
</section>
<section id="section-iv-regression-diagnostics" class="level1">
<h1>Section IV Regression Diagnostics</h1>
<p>In Section IV I confirm my analysis satisfies regression assumptions: linearity, additivity, assumptions about the error terms (specifically, usual cases and homoskedasticity), and multicollinearity. Each assumption requires both an analysis and written explanation.</p>
<section id="section-iv-part-1.-linearity" class="level2">
<h2 class="anchored" data-anchor-id="section-iv-part-1.-linearity">Section IV, Part 1. Linearity</h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">crPlot</span>(tpdlmm, <span class="st">"AmountSum"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec4-lin-1.png" class="img-fluid"><!-- --></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">crPlot</span>(tpwlmm, <span class="st">"AmountSum"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec4-lin-2.png" class="img-fluid"><!-- --></p>
<p>Non-linearity is when the relationship between an independent variable and a dependent variable is not linear, i.e.&nbsp;not a straight line; a curved line. Un-modelled non-linearity is a problem because it means a linear model does not accurately represent the correlation between the outcome and research variable. To test our assumption of linearity, we’ll plot the residuals (the difference between the predicted value of tips and the actual values) of our Tip variable against the order amount. We’re looking for large deviations of residual (traced by a smooth pink line) from the expected values (the dashed blue line), which we don’t see for either hypothesis. This suggests that it’s safe to assume our model is linear.</p>
</section>
<section id="section-iv-part-2.-additivity" class="level2">
<h2 class="anchored" data-anchor-id="section-iv-part-2.-additivity">Section IV, Part 2. Additivity</h2>
<div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dwamint <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSum <span class="sc">~</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation <span class="sc">+</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span><span class="sc">*</span>AmountSum, <span class="at">data=</span>tpp)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dwamint)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSum ~ `Day of Week` + AmountSum + Precipitation + 
##     `Day of Week` * AmountSum, data = tpp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -18.174  -2.754   1.121   2.858  11.131 
## 
## Coefficients:
##                             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                -3.121128   2.827903  -1.104   0.2747    
## `Day of Week`Mon            1.701746   4.370748   0.389   0.6986    
## `Day of Week`Tue            2.952111   4.512479   0.654   0.5158    
## `Day of Week`Wed            0.233517   4.386120   0.053   0.9577    
## `Day of Week`Thu            1.445962   4.177960   0.346   0.7306    
## `Day of Week`Sat            9.135624   3.896596   2.345   0.0228 *  
## `Day of Week`Sun            4.440349   3.997083   1.111   0.2716    
## AmountSum                   0.138684   0.006773  20.475   &lt;2e-16 ***
## PrecipitationLight Rain     1.211983   2.119148   0.572   0.5698    
## PrecipitationNo Rain        0.456024   1.988259   0.229   0.8195    
## PrecipitationHeavy Rain    -0.430723   1.904349  -0.226   0.8219    
## `Day of Week`Mon:AmountSum  0.007140   0.017823   0.401   0.6903    
## `Day of Week`Tue:AmountSum -0.002553   0.018792  -0.136   0.8924    
## `Day of Week`Wed:AmountSum  0.015697   0.012188   1.288   0.2034    
## `Day of Week`Thu:AmountSum -0.006268   0.015640  -0.401   0.6902    
## `Day of Week`Sat:AmountSum -0.015622   0.009431  -1.657   0.1035    
## `Day of Week`Sun:AmountSum  0.006498   0.012400   0.524   0.6025    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.555 on 53 degrees of freedom
## Multiple R-squared:  0.9702, Adjusted R-squared:  0.9612 
## F-statistic: 107.7 on 16 and 53 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>weamint <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSum <span class="sc">~</span> Weekend <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation <span class="sc">+</span> Weekend<span class="sc">*</span>AmountSum, <span class="at">data=</span>tpp)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weamint)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSum ~ Weekend + AmountSum + Precipitation + Weekend * 
##     AmountSum, data = tpp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.3429  -2.9072   0.5624   2.9719  10.8939 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              -2.042655   1.915015  -1.067   0.2902    
## WeekendWeekend            4.130397   2.323774   1.777   0.0803 .  
## AmountSum                 0.146398   0.006993  20.935   &lt;2e-16 ***
## PrecipitationLight Rain   0.466863   2.015268   0.232   0.8176    
## PrecipitationNo Rain      0.512134   1.879861   0.272   0.7862    
## PrecipitationHeavy Rain  -0.233512   1.853469  -0.126   0.9001    
## WeekendWeekend:AmountSum -0.014505   0.008185  -1.772   0.0812 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.731 on 63 degrees of freedom
## Multiple R-squared:  0.9623, Adjusted R-squared:  0.9587 
## F-statistic: 267.7 on 6 and 63 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Non-additivity, also known as an interaction is when the relationship between an independent variable and the outcome variable depends on the values of another variable. Failure to account for interactions makes less accurate linear models. To test additivity, we’ll model an interaction between the day of the week/weekend status and the order amount variable. The reason we’re testing an interaction between these two independent variables, and not precipitation, is because I know from experience that weekends are busier than week days, and therefore have higher values of total order amount. It’s not necessarily that people are ordering more food on weekends, rather there are just more people ordering on weekends. However, even though order amounts are higher on weekends, I believe that people will not be tipping more than their order amount would predict on weekends than weekdays. I hypothesize that the interaction between the day of the week/weekend status will have a negligible correlation with tips, let’s say a positive coefficient that’s less than 1, given that the interaction is in fact significant. To be clear, my additivity hypothesis is a conditional proposition: IF the interaction is significant, THEN the coefficient is positive but less than one.</p>
<p>Since I already have two working hypotheses, I’ll have to test my additivty hypothesis for both models. Interpreting the multiple regression models including the interaction variable, we see that the relationship between total order amount and cash-out amount is not conditional on which day of the week it happens to be, or if it happens to be a weekend. My conditional hypothesis was vacuously true for both models because the interaction was not significant. (A conditional proposition is true when it’s antecedent clause is false.) I could find no significant interactions in my models, so it’s safe to assume our data is additive.</p>
</section>
<section id="section-iv-part-3.-unusual-cases-heteroskedasticity" class="level2">
<h2 class="anchored" data-anchor-id="section-iv-part-3.-unusual-cases-heteroskedasticity">Section IV, Part 3. Unusual cases &amp; heteroskedasticity</h2>
<div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Normality</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tpp, <span class="fu">aes</span>(<span class="at">x=</span>TipSum, <span class="at">y =</span> ..count..))<span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ..count..))<span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Frequency of Cash-outs amounts"</span>)<span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),)<span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec4-homosked-1.png" class="img-fluid"><!-- --></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>logdlmm <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSumLog <span class="sc">~</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation, <span class="at">data=</span>tpp)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logdlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSumLog ~ `Day of Week` + AmountSum + Precipitation, 
##     data = tpp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.89039 -0.14611  0.09825  0.28043  0.58108 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              2.3603002  0.1759364  13.416   &lt;2e-16 ***
## `Day of Week`Mon         0.1169072  0.1974117   0.592    0.556    
## `Day of Week`Tue        -0.0132046  0.2042128  -0.065    0.949    
## `Day of Week`Wed         0.0163281  0.2215474   0.074    0.941    
## `Day of Week`Thu        -0.2435917  0.2183594  -1.116    0.269    
## `Day of Week`Sat         0.1393906  0.1963120   0.710    0.480    
## `Day of Week`Sun         0.0600420  0.2000636   0.300    0.765    
## AmountSum                0.0034462  0.0002981  11.562   &lt;2e-16 ***
## PrecipitationLight Rain  0.0492576  0.1651029   0.298    0.766    
## PrecipitationNo Rain     0.0061726  0.1571246   0.039    0.969    
## PrecipitationHeavy Rain -0.1019849  0.1530241  -0.666    0.508    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4637 on 59 degrees of freedom
## Multiple R-squared:  0.7426, Adjusted R-squared:  0.699 
## F-statistic: 17.02 on 10 and 59 DF,  p-value: 5.693e-14</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>logwlmm <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSumLog <span class="sc">~</span> Weekend <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation, <span class="at">data=</span>tpp)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logwlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSumLog ~ Weekend + AmountSum + Precipitation, 
##     data = tpp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8616 -0.1996  0.1139  0.3116  0.5145 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              2.339504   0.116325  20.112   &lt;2e-16 ***
## WeekendWeekend           0.080292   0.114515   0.701    0.486    
## AmountSum                0.003483   0.000284  12.265   &lt;2e-16 ***
## PrecipitationLight Rain  0.044912   0.160070   0.281    0.780    
## PrecipitationNo Rain    -0.022885   0.148774  -0.154    0.878    
## PrecipitationHeavy Rain -0.095057   0.146373  -0.649    0.518    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4576 on 64 degrees of freedom
## Multiple R-squared:  0.7281, Adjusted R-squared:  0.7069 
## F-statistic: 34.28 on 5 and 64 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tpp, <span class="fu">aes</span>(<span class="at">x=</span>TipSumLog, <span class="at">y =</span> ..count..))<span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ..count..))<span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Frequency of Cash-outs amounts"</span>)<span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),)<span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec4-homosked-2.png" class="img-fluid"><!-- --></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(logdlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##     rstudent unadjusted p-value Bonferroni p
## 27 -5.370143         1.4486e-06    0.0001014
## 53 -4.506757         3.2454e-05    0.0022718</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(logwlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##     rstudent unadjusted p-value Bonferroni p
## 27 -5.095281         3.4066e-06   0.00023846
## 53 -4.164164         9.6757e-05   0.00677300</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Heteroskedasticity</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(logdlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 2.205876, Df = 1, p = 0.13749</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncvTest</span>(logwlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 1.472684, Df = 1, p = 0.22492</code></pre>
<p>A big problem I should’ve addressed first is outliers and skewness, AKA non-normality. Normality is the assumption that the error terms of a linear model are random, and do not follow any predictable pattern. Failing to account for predictable patterns in the distribution of error terms suggests that our regression model is missing some information about the relationship between the independent variable(s) and the outcome variable. This can happen when a few large outliers skew the distribution of observations. Just looking at the distribution of cash-outs, we can visually determine that our data is right skewed. To determine if there are any outliers, I used the Bonferroni Outlier Test, which uses a t-distribution to test whether the model’s largest studentized error terms outlier status are significantly different from other observations in the model. But before searching for any outliers, let’s look at our model after a log transformation. The log transformation will standardize the outcome variable, removing the natural skewness of our data set. Applying Bonferroni outlier test after the log transformation shows that observation 27 and 53 are outliers. This suggests our model violates the assumption of normality.</p>
<p>Moving on, let’s test for heteroskedasticity. Heteroskedastcity is the violation of the homoscedasticity assumption, which is the assumption that the error terms is the same across observation, and does not dependent on the values of the independent variables. Heteroskedasticity refers to a systematic change in the variance of the residuals of the range of observations, i.e.&nbsp;non-constant variance. To diagnose non-constant variance in our observations, I used the non-constant variance score test on our log-transformed regression model, which determines if there is non-constant variance in our model. Any significant p-values would mean our data suffers from heteroskedasticity, but fortunately we do not see that issue. It’s safe to assume our model is homoscedastic.</p>
</section>
<section id="section-iv-part-4.-multicollinearity" class="level2">
<h2 class="anchored" data-anchor-id="section-iv-part-4.-multicollinearity">Section IV, Part 4. Multicollinearity</h2>
<div class="sourceCode" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(logdlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##                   GVIF Df GVIF^(1/(2*Df))
## `Day of Week` 1.325119  6        1.023736
## AmountSum     1.164461  1        1.079102
## Precipitation 1.205530  3        1.031644</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(logwlmm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>##                   GVIF Df GVIF^(1/(2*Df))
## Weekend       1.095035  1        1.046439
## AmountSum     1.085621  1        1.041931
## Precipitation 1.053302  3        1.008693</code></pre>
<p>The fifth assumption of regression is that there is no perfect (multi)collinearity in our model. Multicolinearity is when two or more variables are highly linearly related. Even if our model is not perfectly multicollinearly related, imperfect or near multiconllinearity is still an issue because it can erroneously inflate variance. Although I have no theoretical reason to believe that any of our independent variables are perfect collinearities, or anywhere near perfect, to be safe I ran a Variance Inflation Factor test, which measures how much collinearity has increased the variance of our coefficients. As a rule of thumb, any VIF score above 5 is considered problematic for the regression model. Fortunately, I saw no evidence of multicollinearity in either of my regression models. It’s safe to assume our model has no perfect (or near perfect) multicollinearity.</p>
</section>
<section id="section-iv-part-5.-correcting-assumptions-of-linearity" class="level2">
<h2 class="anchored" data-anchor-id="section-iv-part-5.-correcting-assumptions-of-linearity">Section IV, Part 5. Correcting Assumptions of Linearity</h2>
<div class="sourceCode" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tppP <span class="ot">&lt;-</span> tpp[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">53</span>, <span class="dv">27</span>), ]</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tppP, <span class="fu">aes</span>(<span class="at">x=</span>TipSumLog, <span class="at">y =</span> ..count..))<span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ..count..))<span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Frequency of Cash-outs amounts"</span>)<span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),)<span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec4-revised-model-1.png" class="img-fluid"><!-- --></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>logdlmP <span class="ot">&lt;-</span> <span class="fu">lm</span>(TipSumLog <span class="sc">~</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span> <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation <span class="sc">+</span> <span class="st">`</span><span class="at">Day of Week</span><span class="st">`</span><span class="sc">*</span>AmountSum, <span class="at">data=</span>tppP)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>logwlmP <span class="ot">&lt;-</span><span class="fu">lm</span>(TipSumLog <span class="sc">~</span> Weekend <span class="sc">+</span> AmountSum <span class="sc">+</span> Precipitation <span class="sc">+</span> Weekend<span class="sc">*</span>AmountSum, <span class="at">data=</span>tppP)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logdlmP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSumLog ~ `Day of Week` + AmountSum + Precipitation + 
##     `Day of Week` * AmountSum, data = tppP)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.87542 -0.14852  0.00736  0.18074  0.62518 
## 
## Coefficients:
##                              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 2.5461060  0.1481832  17.182  &lt; 2e-16 ***
## `Day of Week`Mon           -0.3861386  0.2287637  -1.688 0.097530 .  
## `Day of Week`Tue           -0.7910592  0.2363071  -3.348 0.001538 ** 
## `Day of Week`Wed           -0.4357577  0.2295328  -1.898 0.063302 .  
## `Day of Week`Thu           -0.9374053  0.2186739  -4.287 8.06e-05 ***
## `Day of Week`Sat            0.4065877  0.2044088   1.989 0.052068 .  
## `Day of Week`Sun           -0.0589708  0.2234873  -0.264 0.792946    
## AmountSum                   0.0027443  0.0003547   7.737 3.75e-10 ***
## PrecipitationLight Rain     0.1152533  0.1136880   1.014 0.315479    
## PrecipitationNo Rain        0.0226268  0.1050532   0.215 0.830327    
## PrecipitationHeavy Rain    -0.0234668  0.0998079  -0.235 0.815058    
## `Day of Week`Mon:AmountSum  0.0022023  0.0009333   2.360 0.022153 *  
## `Day of Week`Tue:AmountSum  0.0039048  0.0009838   3.969 0.000226 ***
## `Day of Week`Wed:AmountSum  0.0015419  0.0006378   2.417 0.019246 *  
## `Day of Week`Thu:AmountSum  0.0033310  0.0008186   4.069 0.000164 ***
## `Day of Week`Sat:AmountSum -0.0006871  0.0004949  -1.388 0.171036    
## `Day of Week`Sun:AmountSum  0.0009261  0.0006879   1.346 0.184163    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2907 on 51 degrees of freedom
## Multiple R-squared:  0.8974, Adjusted R-squared:  0.8652 
## F-statistic: 27.88 on 16 and 51 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logwlmP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## 
## Call:
## lm(formula = TipSumLog ~ Weekend + AmountSum + Precipitation + 
##     Weekend * AmountSum, data = tppP)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.86502 -0.15816  0.07118  0.21065  0.42562 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               1.9868741  0.1072993  18.517  &lt; 2e-16 ***
## WeekendWeekend            0.7235010  0.1320068   5.481 8.54e-07 ***
## AmountSum                 0.0050728  0.0003922  12.934  &lt; 2e-16 ***
## PrecipitationLight Rain   0.0772306  0.1154402   0.669    0.506    
## PrecipitationNo Rain      0.0407318  0.1073184   0.380    0.706    
## PrecipitationHeavy Rain  -0.0283925  0.1037984  -0.274    0.785    
## WeekendWeekend:AmountSum -0.0025113  0.0004591  -5.470 8.89e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3209 on 61 degrees of freedom
## Multiple R-squared:  0.8505, Adjusted R-squared:  0.8358 
## F-statistic: 57.83 on 6 and 61 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">exp</span>(<span class="fu">coef</span>(logwlmP)[<span class="st">"WeekendWeekend"</span>]) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>## WeekendWeekend 
##       106.1638</code></pre>
<p>The biggest issue in my model was non-normality. I fixed this by logarithmic transformation of my outcome variable to standardize the distribution of cash-outs, and then taking out the outliers. After removing those outliers, we see a much more normal distribution in our cash-outs. The last steps are to re-estimate our linear model including our interaction variable. We finally have 2 final linear models for both our hypotheses that do not violate the assumptions of linear regression.</p>
<p>The model for our first hypothesis didn’t see enough significant results.</p>
<p>The model for our second hypothesis did create significant results. Since we took the log transformation of our outcome variable, to interpret the result we must work backwards to interpret the log value of cash-outs on weekends, like so <img src="https://latex.codecogs.com/png.image?%5Cdpi%7B110%7D&amp;space;%5Cbg_white&amp;space;%28exp%28coef%28logwlmP%29%5B%22WeekendWeekend%22%5D%29%20-%201%29%20%2A%20100" title="(exp(coef(logwlmP)[&quot;WeekendWeekend&quot;]) - 1) * 100" class="img-fluid" alt="(exp(coef(logwlmP)$$“WeekendWeekend”$$) - 1) * 100">, which is equal to %106.16. Our linear model predicts that on weekends (Fridays, Saturdays and Sundays), we make %106.16 more tips than on weekdays.</p>
</section>
</section>
<section id="section-v.-conclusion" class="level1">
<h1>Section V. Conclusion</h1>
<p>After some processing, we finally have enough information to assess our hypotheses. Our first hypothesis, that on average the best three days for cash-outs were Saturdays, Fridays and Sundays in that order was assessed with a linear model accounting for non-normality and non-additivity, and did not find sufficient evidence to reject the null hypothesis that Saturdays, Fridays and Sundays are not the best three days for cash-outs. However, our secondary hypothesis, that Weekends (Fridays, Saturdays and Sundays) have on average higher cash-outs than Weekdays (Mondays, Tuesdays, Wednesdays and Thursday), which was assessed via a linear regression model accounting for non-normality and non-additivity did see sufficient evidence to reject the null hypothesis. I can say with confidence that working weekends is more lucrative than working weekdays, and I will schedule my shifts accordingly to maximize my income.Furthermore, I didn’t see any significant results which indicated that higher levels of precipitation are correlated at all with tips.</p>
<p>There’s another interesting outcome of this research that surprised me. When looking at the frequency distribution of tips represented as a percentage of the sale amount (see figure below), we see tips generally gravitate towards 5 buckets: 12%, 15%, 16%, 18% and 20%. My initial explanation for this distribution was that when paying for their orders customers tend to defer to the preset tip-percentage amounts, with 15% being the cultural norm. But this explanation fails because each credit machine only has 3 preset tip percentage options to choose from, which would predict 3 spikes in frequency at those percentages, not 5 spikes. However, after some detective work I learned that some of the credit-machines were programmed with different preset tip percentage options than others. Some were programmed with the presets 12%, 16%, 18%, some with 15%, 18%, 20%, for a total of 5 possible outcomes. Not only does this realization solve this mystery, it offers me a new means of maximizing my tip money: when going on a delivery choose a credit-machine with the higher tip preset options.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Tip Percent Frequency</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(s, <span class="fu">aes</span>(<span class="at">x=</span>TipPercent, <span class="at">y =</span> ..count..))<span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> ..count..), <span class="at">binwidth =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>)) <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>))<span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Frequency of Tip Percent"</span>)<span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="fu">min</span>(s<span class="sc">$</span>TipPercent), <span class="fu">max</span>(s<span class="sc">$</span>TipPercent), <span class="dv">1</span>),</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">name=</span><span class="st">"Tip Percent"</span>)<span class="sc">+</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>, <span class="at">panel.border =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="Pizza-Delivery-Tip-Maxxing-Part-1_files/figure-gfm/sec5-1.png" class="img-fluid"><!-- --></p>
<p>At the end of the day, although I’m confident in my regression model prediction, I recognize the limitations of my data. Above all, my data collection process leaves room for improvement. There needs to be a more systematic way of recording sales data and driver activity to make a more comprehensive and larger scale statistical analysis. Furthermore, although I refer to this data as my own, in reality this data was collected via a handful of different delivery drivers. I could not differentiate between an order I took and an order another driver took by looking at the receipt, which leaves me wondering if some drivers get tipped more than others. If so, what properties do those drivers possess? I suspect the correlation between looks and tips is a well studied phenomenon in waitresses, but I wonder what such a study could look like for male delivery drivers like myself.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The pedantic reader will have noticed that I classified Friday as a weekend and consequently shook their head in disapproval. “Only Saturdays and Sundays are weekends. Fridays are weekdays.”, they might reproach. This traditional calendar taxonomy, garbed in an ontological gloss is at best a social convention, and certainly not an objective property of time itself (assuming time as such could have such properties). For the purposes of this study, it’s safe to reject this convention and replace it with one that is more practical for it’s ends. I work three days a week, so if I happen to demonstrate that weekends are better than weekdays in terms of tips, I can simply schedule myself to work on Friday, Saturday and Sunday. If the pendant persists in his pedantry, we need not use the terms “Weekend” and “Weekday”, we can instead simply refer to the set of days containing “Friday, Saturday and Sunday”, and the set containing “Monday, Tuesday, Wednesday and Thursday”.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Observation 37 had a TipSum value of 0, which means I could not take the log of the variable without dealing with the zero. I decided to drop the observation because a $0 cash-out is very unlucky, and is almost certainly an outlier in our data set.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>